//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsApp.WSElectricEnergy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSElectricEnergy.IWSElectricEnergy")]
    public interface IWSElectricEnergy {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSElectricEnergy/GetData", ReplyAction="http://tempuri.org/IWSElectricEnergy/GetDataResponse")]
        MiWCF.EEData GetData(string information);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSElectricEnergy/GetData", ReplyAction="http://tempuri.org/IWSElectricEnergy/GetDataResponse")]
        System.Threading.Tasks.Task<MiWCF.EEData> GetDataAsync(string information);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSElectricEnergyChannel : WindowsApp.WSElectricEnergy.IWSElectricEnergy, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSElectricEnergyClient : System.ServiceModel.ClientBase<WindowsApp.WSElectricEnergy.IWSElectricEnergy>, WindowsApp.WSElectricEnergy.IWSElectricEnergy {
        
        public WSElectricEnergyClient() {
        }
        
        public WSElectricEnergyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSElectricEnergyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSElectricEnergyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSElectricEnergyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MiWCF.EEData GetData(string information) {
            return base.Channel.GetData(information);
        }
        
        public System.Threading.Tasks.Task<MiWCF.EEData> GetDataAsync(string information) {
            return base.Channel.GetDataAsync(information);
        }
    }
}
